#define CEC_DEV_CONTRAST_CODE 0x20
#define CEC_DEV_HUE_CODE 0x1d
#define CEC_DEV_LUMINOSITY_CODE 0x21
#define CEC_DEV_PIVOT_CODE 0x1f
#define CEC_DEV_SATURATION_CODE 0x1e
#define CEC_DEV_SHUTTER_SPEED_CODE 0x57
#define CEC_DEV_TINT_CODE 0x55
#define CEC_DEV_WHITE_BALANCE_TEMP 0x54
